import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import ts from 'typescript';
const source=fs.readFileSync(process.env.PICK_PACK_SOURCE || 'public/app.js','utf8');
const ast=ts.createSourceFile('app.js',source,99,true);
function add(c,...names){for(const name of names){const n=ast.statements.filter(n=>ts.isFunctionDeclaration(n)&&n.name?.text===name);assert.equal(n.length,1,name);vm.runInContext(n[0].getText(ast),c)}}
function env(extra={}){const c={console:{warn(){},error(){}},navigator:{onLine:true},localStorage:{getItem:()=> 'Operador'},...extra};vm.createContext(c);vm.runInContext('const operationalWriteChains=new Map();',c);return c;}
const pack=(id,qty,sessionId='S',complete=false)=>({id,type:'supabase_pick_packages',payload:{sessionId,validateComplete:complete,pacotes:[{quantidade:qty}]}});
const item=(id,delta,sessionId='S')=>({id,type:'supabase_progress',payload:{flow:'separacao',sessionId,delta}});
function queueEnv(initial,options={}){let rows=initial;const sent=[],marks=[],seen=new Set();const server={qty:options.qty||0,packages:0};const c=env({getQueuedOperations:async()=>rows,isPickPackOperation:()=>true,executeQueuedOperation:async op=>{sent.push(op.id);if(op.id===options.fail)throw Error('rede');if(op.type==='supabase_progress'){if(!seen.has(op.id)){server.qty=Math.max(0,server.qty+op.payload.delta);seen.add(op.id)}}else if(op.type==='supabase_pick_packages'){const q=op.payload.pacotes[0].quantidade;if(q>server.qty)throw Error('Produto nao pertence a separacao');server.packages=q;}},markQueuedOperation:async(op,status)=>{marks.push([op.id,status]);if(status==='synced')rows=rows.filter(x=>x.id!==op.id)},refreshOutboxPendingCount(){}});add(c,'drainOperationOutbox');return {c,sent,marks,server,rows:()=>rows,options};}
test('pacote anterior ao primeiro bip nao bloqueia quantidade no outro aparelho',async()=>{const e=queueEnv([pack('p',2),item('i',2)]);await e.c.drainOperationOutbox('test',true);assert.equal(e.server.qty,2);assert.equal(e.server.packages,2);assert.deepEqual(e.sent,['i','p']);assert.equal(e.rows().length,0)});
test('exclusao e novos bipes substituem pacote antigo sem perder quantidades',async()=>{const e=queueEnv([pack('antigo',5),item('excluir',-5),item('novo',3),pack('atual',3)],{qty:5});await e.c.drainOperationOutbox('test',true);assert.deepEqual(e.sent,['excluir','novo','atual']);assert.equal(e.server.qty,3);assert.equal(e.server.packages,3);assert.equal(e.rows().length,0)});
test('erro no bip preserva pacotes e operacoes posteriores',async()=>{const e=queueEnv([pack('p',1),item('erro',1),item('depois',2)],{fail:'erro'});await e.c.drainOperationOutbox('test',true);assert.deepEqual(e.sent,['erro']);assert.equal(e.rows().length,3);assert.equal(e.server.packages,0)});
test('repetir envio apos falha nao duplica quantidades nem descarta retratos antes de sucesso',async()=>{const e=queueEnv([pack('old',1),item('i',2),pack('latest',2)],{fail:'latest'});await e.c.drainOperationOutbox('test',true);assert.equal(e.server.qty,2);assert.deepEqual(e.rows().map(x=>x.id),['old','latest']);e.options.fail=null;await e.c.drainOperationOutbox('retry',true);assert.equal(e.server.qty,2);assert.equal(e.server.packages,2);assert.equal(e.rows().length,0)});
test('pacote completo substitui rascunhos somente apos sucesso',async()=>{const e=queueEnv([pack('old',9),item('i',2),pack('complete',2,'S',true)]);await e.c.drainOperationOutbox('test',true);assert.deepEqual(e.sent,['i','complete']);assert.equal(e.rows().length,0)});
test('conferencia aguarda pacote e nunca ultrapassa pacote rejeitado',async()=>{const e=queueEnv([pack('p',3),{id:'conf',type:'supabase_pick_create_conference',payload:{sessionId:'S'}}]);await e.c.drainOperationOutbox('test',true);assert.deepEqual(e.sent,['p']);assert.equal(e.rows().length,2)});
test('pacotes de sessoes distintas nao sao substituidos entre si',async()=>{const e=queueEnv([pack('a',1,'A'),pack('b',1,'B'),item('i',1)]);await e.c.drainOperationOutbox('test',true);assert.deepEqual(e.sent,['i','a','b']);assert.equal(e.rows().length,0)});
function pauseEnv({empty=false,pending=false,offline=false,fail=false}={}){const events=[],messages=[];let saved;const c=env({navigator:{onLine:!offline},currentSessionItems:empty?[]:[{qty:3}],currentPickingContext:{sessionId:'S'},isValidPickSessionId:()=>true,sanitizePickSessionIdForChannel:x=>x,saveDraftPickSession:d=>{saved=d;return d},PICK_STATUS_DRAFT:'rascunho',getDataHoraBrasil:()=> 'agora',generateExecutionId:()=> 'id',getCurrentPickPackageCount:()=>empty?0:3,persistPickingDraftItemsBatch:async()=>{events.push('itens');if(fail)throw Error('disco')},persistPickingDraftSession:async()=>events.push('cabecalho'),clearTimeout(){},pickPackageCloudSyncTimer:null,pendingPickPackageSnapshot:null,syncPickPackagesWithCloud:async o=>{events.push('pacotes');assert.equal(o.items.length,empty?0:1)},getQueuedOperations:async()=>pending?[item('i',1)]:[],markDraftPickSaveStatus:s=>events.push(s),showToast:m=>messages.push(m),renderPickMenu:()=>events.push('menu')});add(c,'pausePickingSession');return {c,events,messages,saved:()=>saved};}
test('pausa confirma itens e pacotes antes de declarar sincronizada',async()=>{const e=pauseEnv();await e.c.pausePickingSession('S','C','Canal','cor');assert.deepEqual(e.events,['itens','cabecalho','pacotes','synced','menu']);assert.match(e.messages[0],/sincronizada/)});
test('pausa com cabecalho salvo mas bipes pendentes nao anuncia sincronizada',async()=>{const e=pauseEnv({pending:true});await e.c.pausePickingSession('S','C','Canal','cor');assert.ok(e.events.includes('queued'));assert.match(e.messages[0],/quantidades aguardando envio/)});
test('pausa vazia preserva separacao e envia remocoes, sem apagar rascunho',async()=>{const e=pauseEnv({empty:true,pending:true});await e.c.pausePickingSession('S','C','Canal','cor');assert.equal(e.saved().items.length,0);assert.deepEqual(e.events,['itens','cabecalho','pacotes','queued','menu'])});
test('falha ao preservar itens nao e mascarada pelo salvamento do cabecalho',async()=>{const e=pauseEnv({fail:true});await e.c.pausePickingSession('S','C','Canal','cor');assert.deepEqual(e.events,['itens','failed','menu']);assert.match(e.messages[0],/pendente/)});
test('pausa offline informa que ainda precisa enviar as quantidades',async()=>{const e=pauseEnv({offline:true});await e.c.pausePickingSession('S','C','Canal','cor');assert.ok(e.events.includes('queued'))});
test('retomada recupera ultimo retrato local antes de recarregar outro aparelho',async()=>{let rows=[pack('stale',8),item('i',3)];const events=[];const c=env({pickPackageCloudSyncTimer:null,pickPackageCloudSyncChain:Promise.resolve(),getLocalDraftPickSession:()=>({sessionId:'S',items:[{qty:3}]}),getQueuedOperations:async()=>rows,persistPickingDraftItemsBatch:async()=>events.push('itens'),syncPickPackagesWithCloud:async o=>{assert.equal(o.items[0].qty,3);events.push('pacotes');rows=[]},flushConferenceProgressSync:async()=>events.push('flush'),showToast(){}});add(c,'isPickPackOperation','preparePickPackResume');assert.equal(await c.preparePickPackResume('S'),true);assert.deepEqual(events,['itens','pacotes','flush'])});
test('retomada nao recria pacotes quando ha finalizacao pendente',async()=>{let regenerated=false;const c=env({pickPackageCloudSyncTimer:null,pickPackageCloudSyncChain:Promise.resolve(),getLocalDraftPickSession:()=>({items:[]}),getQueuedOperations:async()=>[pack('p',1),{type:'supabase_pick_finalize',payload:{sessionId:'S'}}],persistPickingDraftItemsBatch:async()=>{regenerated=true},flushConferenceProgressSync:async()=>{},showToast(){}});add(c,'isPickPackOperation','preparePickPackResume');assert.equal(await c.preparePickPackResume('S'),false);assert.equal(regenerated,false)});

test('confirma retratos antigos antes do atual para permitir retomada apos fechamento',async()=>{const e=queueEnv([pack('old',1),pack('latest',2),item('i',2)]);await e.c.drainOperationOutbox('test',true);assert.deepEqual(e.marks.filter(x=>x[1]==='synced').map(x=>x[0]),['i','old','latest'])});
