import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import ts from 'typescript';
const source=fs.readFileSync(process.env.PICK_PACK_SOURCE || 'public/app.js','utf8');
const ast=ts.createSourceFile('app.js',source,99,true);
const code=name=>{const nodes=ast.statements.filter(n=>ts.isFunctionDeclaration(n)&&n.name?.text===name);assert.equal(nodes.length,1,name);return nodes[0].getText(ast)};
function env(extra={}) {const c={console:{log(){},warn(){},error(){}},navigator:{onLine:true},localStorage:{getItem:()=> 'Teste'},...extra};vm.createContext(c);vm.runInContext('const operationalWriteChains = new Map(); let pickPackageCloudSyncChain = Promise.resolve();',c);return c;}
function add(c,...names){vm.runInContext(names.map(code).join('\n'),c)}
const progress=(id,sessionId='S')=>({id,type:'supabase_progress',payload:{flow:'separacao',sessionId},meta:{sessionId}});
const stale={id:'old',type:'supabase_pick_packages',payload:{sessionId:'S',validateComplete:false}};
test('quantidade zero permanece zero mesmo com quantidade antiga no item',()=>{const c=env({isUsableProductScanCode:()=>false,isHomologationEnvironment:()=>false});add(c,'buildPickingItemPayload');assert.equal(c.buildPickingItemPayload({qty:0,qtd_separada:4}).qtd_separada,0);});
test('exclusao completa zera quantidade; remocao parcial preserva restante',async()=>{const sent=[];const c=env({persistPickingDraftItem:async(d,i)=>{sent.push(i.qty);return {queued:true}},markDraftPickSaveStatus(){}});add(c,'persistPickingItemRemoval');await c.persistPickingItemRemoval({}, {qty:4},true);await c.persistPickingItemRemoval({}, {qty:3},false);assert.deepEqual(sent,[0,3]);});
test('pacote antigo nao impede enviar item e somente a separacao atual e enviada',async()=>{let rows=[stale,progress('p'),progress('outro','T')];const sent=[];const c=env({getQueuedOperations:async()=>rows,executeQueuedOperation:async o=>{sent.push(o.id)},markQueuedOperation:async o=>{rows=rows.filter(r=>r.id!==o.id)},refreshOutboxPendingCount(){}});add(c,'runOperationalWrite','flushPickingItemsBeforeFinalization');assert.equal((await c.flushPickingItemsBeforeFinalization('S')).queued,false);assert.deepEqual(sent,['p']);assert.deepEqual(rows.map(r=>r.id),['old','outro']);});
test('falha de rede mantem item pendente sem concluir',async()=>{const marks=[];const c=env({getQueuedOperations:async()=>[progress('p')],executeQueuedOperation:async()=>{throw Error('offline')},markQueuedOperation:async(o,s)=>marks.push(s),isRetryableConferenceSyncError:()=>true});add(c,'runOperationalWrite','flushPickingItemsBeforeFinalization');assert.equal((await c.flushPickingItemsBeforeFinalization('S')).queued,true);assert.deepEqual(marks,['error']);});
test('falha definitiva no item impede finalizar',async()=>{const c=env({getQueuedOperations:async()=>[progress('p')],executeQueuedOperation:async()=>{throw Error('rejeitado')},markQueuedOperation(){},isRetryableConferenceSyncError:()=>false});add(c,'runOperationalWrite','flushPickingItemsBeforeFinalization');await assert.rejects(c.flushPickingItemsBeforeFinalization('S'),/rejeitado/);});
test('finalizacao nao ultrapassa exclusao pendente da sessao',async()=>{const c=env({getQueuedOperations:async()=>[{id:'d',type:'supabase_pick_draft_delete',payload:{sessionId:'S'}}]});add(c,'runOperationalWrite','flushPickingItemsBeforeFinalization');await assert.rejects(c.flushPickingItemsBeforeFinalization('S'),/exclusao pendente/);});
test('offline nao tenta acessar banco',async()=>{const c=env({navigator:{onLine:false}});add(c,'flushPickingItemsBeforeFinalization');assert.equal((await c.flushPickingItemsBeforeFinalization('S')).queued,true);});
function finalEnv({queued=false,packageError=false}={}){
 const events=[];const c=env({isFinalizing:false,showToast(){},currentPickingContext:{sessionId:'S'},currentPickSession:{items:[{id_interno:'DY-000.050',qty:1}],pickingData:{}},sanitizePickSessionIdForChannel:x=>x,assertValidPickSessionForPersist(){},getPickingOperationalStats:()=>({total_produtos_separados:1,total_itens_separados:1,total_pacotes_montados:1}),clearTimeout(){},pickPackageCloudSyncTimer:null,ensureProdutosLoaded:async()=>{},getDataHoraBrasil:()=> 'agora',getScopedDraftPickSession:()=>({sessionId:'S'}),getActivePickingFastMode:()=>false,buildPickingSessionPayload:()=>({}),PICK_STATUS_READY_FOR_PACK:'aguardando',PICK_STATUS_DRAFT:'rascunho',PICK_MANUAL_OBSERVATION:'manual',persistPickingDraftItemsBatch:async()=>({queued:true}),flushPickingItemsBeforeFinalization:async()=>{events.push('itens');return {queued}},getQueuedOperations:async()=>[stale,{...stale,id:'other',payload:{sessionId:'T'}}],runOperationalWrite:async(k,work)=>work(),performPickPackagesCloudSync:async o=>{events.push('pacotes');assert.equal(o.forceQueue,queued);if(packageError)throw Error('falha pacote');return {queued}},markQueuedOperation:async o=>{events.push('substituido:'+o.id)},buildFastPickingFinalRows:()=>[],generateExecutionId:()=> 'id',queueOperation:async(type)=>events.push(type),createPickingConferenceWithoutStock:async()=>events.push('conferencia'),persistPickingFinal:async(id,force)=>{events.push('final:'+force);throw Error('fim do teste')},showAppModal:async()=>{}});add(c,'savePickResultFinal');return {c,events};
}
test('finalizacao envia itens antes de pacotes e so depois cria conferencia',async()=>{const {c,events}=finalEnv();await c.savePickResultFinal('S','C','Canal','cor');assert.deepEqual(events,['itens','pacotes','substituido:old','conferencia','final:false']);});
test('pendencia coloca conferencia e finalizacao na fila mesmo com navegador online',async()=>{const {c,events}=finalEnv({queued:true});await c.savePickResultFinal('S','C','Canal','cor');assert.deepEqual(events,['itens','pacotes','substituido:old','supabase_pick_create_conference','final:true']);});
test('erro ao salvar pacotes preserva rascunhos e nao cria conferencia',async()=>{const {c,events}=finalEnv({packageError:true});await c.savePickResultFinal('S','C','Canal','cor');assert.deepEqual(events,['itens','pacotes']);});
test('pacotes com dependencia pendente sao gravados na fila, nunca enviados diretamente',async()=>{const events=[];const c=env({isTemporaryPickSessionId:()=>false,isValidPickSessionId:()=>true,currentSessionItems:[],buildPickPackagesSyncPayload:()=>[],document:{getElementById:()=>null},queueOperation:async t=>events.push(t),markDraftPickSaveStatus(){}});add(c,'performPickPackagesCloudSync');assert.equal((await c.performPickPackagesCloudSync({sessionId:'S',validateComplete:true,forceQueue:true})).queued,true);assert.deepEqual(events,['supabase_pick_packages']);});
