-- Homologacao: permite finalizar conferencia com divergencia conscientemente autorizada.
ALTER TABLE public.conferencia
    ADD COLUMN IF NOT EXISTS divergencia_autorizada boolean NOT NULL DEFAULT false,
    ADD COLUMN IF NOT EXISTS motivo_divergencia text,
    ADD COLUMN IF NOT EXISTS resumo_divergencia jsonb;

CREATE TABLE IF NOT EXISTS public.conferencia_ajustes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conferencia_id text NOT NULL REFERENCES public.conferencia(conferencia_id) ON DELETE CASCADE,
    separacao_id text NOT NULL,
    id_interno text NOT NULL,
    ean text,
    descricao text,
    qtd_separada integer NOT NULL DEFAULT 0,
    qtd_conferida integer NOT NULL DEFAULT 0,
    diferenca integer NOT NULL DEFAULT 0,
    motivo text NOT NULL,
    autorizado_por text NOT NULL,
    autorizado_em timestamp without time zone NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS conferencia_ajustes_separacao_idx
    ON public.conferencia_ajustes(separacao_id, autorizado_em DESC);

ALTER TABLE public.conferencia_ajustes ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS conferencia_ajustes_select_all ON public.conferencia_ajustes;
CREATE POLICY conferencia_ajustes_select_all ON public.conferencia_ajustes FOR SELECT TO anon, authenticated USING (true);
GRANT SELECT ON public.conferencia_ajustes TO anon, authenticated;

DO $migration$
DECLARE
    v_oid oid;
    v_sql text;
    v_old text;
    v_new text;
BEGIN
    IF to_regprocedure('public.finalizar_conferencia_com_estoque(text,text,jsonb,text)') IS NOT NULL THEN
        v_oid := 'public.finalizar_conferencia_com_estoque(text,text,jsonb,text)'::regprocedure;
    ELSE
        v_oid := 'public.finalizar_conferencia(text,text,jsonb,text)'::regprocedure;
    END IF;
    SELECT replace(pg_get_functiondef(v_oid), chr(13), '') INTO v_sql;

    v_old := '    v_allowed_locals text[] := ARRAY[''TERREO'', ''MOSTRUARIO''];';
    v_new := v_old || E'\n    v_divergencia_autorizada boolean := false;\n    v_motivo_divergencia text;\n    v_resumo_divergencia jsonb;';
    IF position(v_old IN v_sql) = 0 THEN RAISE EXCEPTION 'Declaracao da finalizar_conferencia nao encontrada.'; END IF;
    v_sql := replace(v_sql, v_old, v_new);

    v_old := E'BEGIN\n    IF NULLIF(btrim(p_session_id), '''') IS NULL THEN';
    v_new := E'BEGIN\n    v_divergencia_autorizada := COALESCE((p_rows->0->>''divergencia_autorizada'')::boolean, false);\n    v_motivo_divergencia := NULLIF(btrim(COALESCE(p_rows->0->>''motivo_divergencia'', '''')), '''');\n\n    IF v_divergencia_autorizada AND v_motivo_divergencia IS NULL THEN\n        RAISE EXCEPTION ''Informe o motivo para autorizar a divergencia.'';\n    END IF;\n\n    IF NULLIF(btrim(p_session_id), '''') IS NULL THEN';
    IF position(v_old IN v_sql) = 0 THEN RAISE EXCEPTION 'Inicio da finalizar_conferencia nao encontrado.'; END IF;
    v_sql := replace(v_sql, v_old, v_new);

    v_old := E'    IF EXISTS (\n        SELECT 1\n          FROM _finalizar_conferencia_rows\n         WHERE qtd_separada <> qtd_conferida\n            OR divergencia IS NOT NULL\n    ) THEN\n        RAISE EXCEPTION ''A conferencia possui divergencias. Corrija antes de finalizar.'';\n    END IF;';
    v_new := E'    IF EXISTS (\n        SELECT 1\n          FROM _finalizar_conferencia_rows\n         WHERE qtd_separada <> qtd_conferida\n    ) AND NOT v_divergencia_autorizada THEN\n        RAISE EXCEPTION ''A conferencia possui divergencias. Corrija ou autorize o ajuste antes de finalizar.'';\n    END IF;\n\n    SELECT COALESCE(jsonb_agg(jsonb_build_object(\n        ''id_interno'', id_interno, ''ean'', ean, ''descricao'', descricao,\n        ''qtd_separada'', qtd_separada, ''qtd_conferida'', qtd_conferida,\n        ''diferenca'', qtd_conferida - qtd_separada\n    )), ''[]''::jsonb)\n      INTO v_resumo_divergencia\n      FROM _finalizar_conferencia_rows\n     WHERE qtd_separada <> qtd_conferida;';
    IF position(v_old IN v_sql) = 0 THEN RAISE EXCEPTION 'Bloqueio de divergencia nao encontrado.'; END IF;
    v_sql := replace(v_sql, v_old, v_new);

    v_old := '    IF v_sep_items_count > 0 THEN';
    v_new := '    IF v_sep_items_count > 0 AND NOT v_divergencia_autorizada THEN';
    IF position(v_old IN v_sql) = 0 THEN RAISE EXCEPTION 'Validacao da separacao nao encontrada.'; END IF;
    v_sql := replace(v_sql, v_old, v_new);

    v_old := E'        conferido_em,\n        atualizado_em\n    ) VALUES (\n        v_conferencia_id,\n        p_session_id,\n        ''conferido'',\n        p_usuario,\n        v_now,\n        v_now\n    );';
    v_new := E'        conferido_em,\n        atualizado_em,\n        divergencia_autorizada,\n        motivo_divergencia,\n        resumo_divergencia\n    ) VALUES (\n        v_conferencia_id,\n        p_session_id,\n        ''conferido'',\n        p_usuario,\n        v_now,\n        v_now,\n        v_divergencia_autorizada,\n        v_motivo_divergencia,\n        v_resumo_divergencia\n    );';
    IF position(v_old IN v_sql) = 0 THEN RAISE EXCEPTION 'Insert da conferencia nao encontrado.'; END IF;
    v_sql := replace(v_sql, v_old, v_new);

    v_old := E'        qtd_conferida,\n        NULL\n      FROM _finalizar_conferencia_rows;';
    v_new := E'        qtd_conferida,\n        CASE\n            WHEN qtd_conferida > qtd_separada THEN ''SOBRA''\n            WHEN qtd_conferida < qtd_separada THEN ''FALTA''\n            ELSE NULL\n        END\n      FROM _finalizar_conferencia_rows;\n\n    IF v_divergencia_autorizada THEN\n        INSERT INTO public.conferencia_ajustes (\n            conferencia_id, separacao_id, id_interno, ean, descricao,\n            qtd_separada, qtd_conferida, diferenca, motivo, autorizado_por, autorizado_em\n        )\n        SELECT v_conferencia_id, p_session_id, id_interno, ean, descricao,\n               qtd_separada, qtd_conferida, qtd_conferida - qtd_separada,\n               v_motivo_divergencia, p_usuario, v_now\n          FROM _finalizar_conferencia_rows\n         WHERE qtd_separada <> qtd_conferida;\n    END IF;';
    IF position(v_old IN v_sql) = 0 THEN RAISE EXCEPTION 'Insert dos itens nao encontrado.'; END IF;
    v_sql := replace(v_sql, v_old, v_new);

    v_old := E'        ''movimentos'', v_total_movimentos\n    );';
    v_new := E'        ''movimentos'', v_total_movimentos,\n        ''divergencia_autorizada'', v_divergencia_autorizada,\n        ''motivo_divergencia'', v_motivo_divergencia,\n        ''resumo_divergencia'', v_resumo_divergencia\n    );';
    IF position(v_old IN v_sql) = 0 THEN RAISE EXCEPTION 'Retorno da finalizar_conferencia nao encontrado.'; END IF;
    v_sql := replace(v_sql, v_old, v_new);

    EXECUTE v_sql;
END
$migration$;


COMMENT ON COLUMN public.conferencia.divergencia_autorizada IS 'Indica finalizacao consciente com quantidades diferentes da separacao original.';
COMMENT ON COLUMN public.conferencia.motivo_divergencia IS 'Motivo obrigatorio informado pelo conferente para autorizar a diferenca.';
COMMENT ON TABLE public.conferencia_ajustes IS 'Auditoria imutavel das diferencas autorizadas entre separacao e conferencia.';

GRANT EXECUTE ON FUNCTION public.finalizar_conferencia(text,text,jsonb,text) TO anon, authenticated, service_role;
